import { IMenuOutput } from "@/shared/menu/IMenu";

export const menuList: IMenuOutput[] = [
  {
    id: "13245",
    name: "首页",
    path: "/home",
    component: "pages/home/home",
    tabs: [],
    buttonClick: "",
    buttons: [],
    parentId: "000",
    icon: "",
    parentNumber: "",
    microName: "",
    componentName: "home",
    sort: 0,
    isShow: true,
    type: 0,
    children: [],
  },
  {
    id: "132445765",
    name: "系统管理",
    path: "/systemsetting",
    component: "pages/test-page/test-page",
    tabs: [],
    buttonClick: "",
    buttons: [],
    parentId: "000",
    icon: "<DesktopOutlined/>",
    parentNumber: "",
    microName: "",
    componentName: "test-page",
    sort: 0,
    isShow: true,
    type: 0,
    children: [
    {
      id: "asda",
      name: "测试页面",
      path: "/test",
      component: "pages/test-page/test-page",
      tabs: [],
      buttonClick: "",
      buttons: [],
      parentId: "000",
      icon: "",
      parentNumber: "",
      microName: "",
      componentName: "menu-page",
      sort: 0,
      isShow: true,
      type: 0,
      children: [],
    },
    {
      id: "12122212",
      name: "应用信息",
      path: "/application",
      component: "pages/config/application/index",
      tabs: [],
      buttonClick: "",
      buttons: [],
      parentId: "000",
      icon: "",
      parentNumber: "",
      microName: "",
      componentName: "menu-page",
      sort: 0,
      isShow: true,
      type: 0,
      children: [],
    },
    {
      id: "1001",
      name: "环境信息",
      path: "/environment",
      component: "pages/config/environment/index",
      tabs: [],
      buttonClick: "",
      buttons: [],
      parentId: "000",
      icon: "",
      parentNumber: "",
      microName: "",
      componentName: "menu-page",
      sort: 0,
      isShow: true,
      type: 0,
      children: [],
    }],
  }
]